name: Compile and Release PDFC

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x86_64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment for macOS
      run: |
        brew install gcc

    - name: Compile PDFC
      run: |
        gcc -o pdfc-${{ matrix.arch }} pdfc.c
      shell: bash

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: pdfc-${{ matrix.arch }}
        path: pdfc-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: pdfc-${{ matrix.arch }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false

    - name: Upload Release Asset (macOS x86_64)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdfc-x86_64
        asset_name: pdfc-macos-x86_64
        asset_content_type: application/octet-stream
      if: matrix.arch == 'x86_64'

    - name: Upload Release Asset (macOS arm64)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdfc-arm64
        asset_name: pdfc-macos-arm64
        asset_content_type: application/octet-stream
      if: matrix.arch == 'arm64'
